export const GET_CATEGORIES_HIERARCHICALLY = "GET_CATEGORIES_HIERARCHICALLY";

export const GET_CATEGORIES_HIERARCHICALLY_SUCCESS = "GET_CATEGORIES_HIERARCHICALLY_SUCCESS";

export const GET_CATEGORIES_HIERARCHICALLY_FAIL = "GET_CATEGORIES_HIERARCHICALLY_FAIL";

export function getCategories(payload) {
    return {
        type: GET_CATEGORIES_HIERARCHICALLY,
        payload
    };
}